import {BerthCargoDetlSOModel} from "./berthCargoDetlSO.model";
import {BerthInfoDetlSOModel} from "./berthInfoDetlSO.model";
import {BerthRegAttachSOModel} from "./berthRegAttachSO.model";


export class BerthSearchDetailsResultModel {
  rotationNumber: number;
  shippingAgentName: string;
  line: string;
  requestID: number;
  requestStatus: string;
  port: string;
  vesselName: string;
  vesselType: string;
  connectingVessel: string;
  shippingServiceName: string;
  arriveFrom: string;
  sailTo: string;
  tonnage: string;
  loa: string;
  inboundVoyNo: string;
  outboundVoyNo: string;
  dischargCutOff: string;
  estimantedStayHrs: number;
  etaStatus: string;
  errorCode: string;
  errorMessage: string;
  errorStatus: boolean;
  vesselStatus: boolean;
  berthRegCancelStatus: string;
  requestWorkFlowStatus: string;
  eta: string;
  cargoCutOffTime: string;
  etb: string;
  etd: string;
  anchorageDateTime: string;
  layByDateTime: string;
  ata: string;
  atb: string;
  workStartDateTime: string;
  workEndDateTime: string;
  atd: string;
  createdFromDate: string;
  createdToDate: string;
  requestDate: string;
  arrivalDraft: string;
  sailDraft: string;
  airDraft: string;
  additionalServices: string;
  others: string;
  vesselPosition: string;
  remarks: string;
  estimatedDischgMoves: number;
  estimatedLoadMoves: number;
  estimatedOtherMoves: number;
  typeOfOperation: string;
  modeOfOperation: string;
  noOfCranes: number;
  sustainedGears: number;
  noOfHatches: number;
  wrkflwId: string;
  wrkflwStatus: string;
  approverButton: boolean;
  berthCargoDetlSO: BerthCargoDetlSOModel[];
  berthInfoDetlSO: BerthInfoDetlSOModel[];
  berthRegAttachSO: BerthRegAttachSOModel[];
  isDeleted: string;
  createdBy: string;
  createdDate: string;
  lastModifiedBy: string;
  lastModifiedDate: string;
  berthBookingStatus: string;
  operationStatus: string;
  serviceName: string;
  clientCode: string;
  lineMaster: string[];
  portsMaster: string[];
  terminalMaster: string[];
  terminalCode: string;
  isB2bMessage: string;
  clientCodeVerifier: string;
  imoNo: string;
  expiryDate: string;
  rotationImoNo: string;
  rotationExpiryDate: string;
  portName: string;
  isEdi: string;
  channel: string;
  reference: string;
  preferredBerth:string;
  amendRequestStatus:string;
}