import {CommoditydetailsreqModel} from "./commoditydetailsreq.model";
import {ContainerdetailsreqModel} from "./containerdetailsreq.model";
import {DeliveryorderattachModel} from "./deliveryorderattach.model";

export class DeliveryorderreqModel{
  action: string;
  agentDoNumber: string;
  b2bRefNumber: string;
  billofLadingNo: string;
  boxOperator: string;
  boxOperatorMaster: string[];
  cFSCode: string;
  cFSName: string;
  cHACode: string;
  cHAName: string;
  channel: string;
  clientCode: string;
  commodityCode: string;
  commodityDescriptionCargo: string;
  consigneeCode: string;
  consigneeName: string;
  containerPermitDate: string;
  containerPermitNo: string;
  createdDate: string;
  dOValidityDate: string;
  dOValidityExtendedUpto: string;
  delOrdCommodtyDetlSO: CommoditydetailsreqModel[];
  delOrdContDetlSO: ContainerdetailsreqModel[];
  deliveryOrderNo: number;
  deliveryOrderRequestId: number;
  deliveryOrderStatus: string;
  deliveryTo: string;
  depatureMode: string;
  doAttachs: DeliveryorderattachModel[];
  doDboxOperator: string;
  doDrotationNumber: string;
  doForExamination: string;
  doType: string;
  emptyYardCode: string;
  emptyYardName: string;
  fclIGMMRNNo: string;
  frieghtForwarderCode: string;
  frieghtForwarderName: string;
  grossWeightUnit: string;
  haulierCode: string;
  haulierName: string;
  hbillofLadingNo: string;
  importerAddress: string;
  importerName: string;
  instructionsToOtherParty: string;
  isB2bMessage: string;
  isDeleted: string;
  isPGO: string;
  lastModifiedBy: string;
  lastModifiedDate: string;
  lclIGMMRNNo: string;
  msgRefNo: string;
  natureOfCargo: string;
  noOfContainers: string;
  packageDetail: string;
  packageType: string;
  port: string;
  portCode: string;
  portOfDestination: string;
  portOfLoading: string;
  portsMaster: string[];
  requestDate: string;
  requestStatus: string;
  rotationNo: string;
  terminal: string;
  terminalCode: string;
  terminalMaster: string[];
  totalItemNo: string;
  totalNoOfContainers: number;
  totalNoOfPackages: string;
  totalQuantity: string;
  totalWeight: string;
  tradeType: string;
  unitOfQuantity: string;

  iMONoRotation: string;
  rotationNoInfoBTN: string;
  imoNoFCLMrn: string;
  imoNoLCLMrn: string;
  vesselNameFCLMrn: string;
  vesselNameLCLMrn: string;
  vesselNameRotation: string;
  voyageNoFCLMrn: string;
  voyageNoLCLMrn: string;
  voyageNoRotation: string;
  showdetails:boolean=false;


  cargoCommodityCode:string;
  cargoItemDescription:string;
}
