import {DocDetails} from "./voyageenquirydetailsDoc.model";
export class VoyageEnquiryDetailsModel {
   shippingLine:string;
   shippingLineCode:string;
   shippingAgent:string ;
   agentNameCode :string;
   vesselName:string;
   vesselType:string;
   rotationNumber:string;
   portOfArrival:string;
   sailTo:string;
   firstTerminal:string;
   eta:string;
   etb:string;
   etd:string;
   ata:string;
   atb:string;
   atd:string;
   inboundVoyageNumber:string;
   outboundVoyageNumber:string;
   voyageType:string;
   arrivalDraft:string;
   sailingDraft:string;
   airDraft:string;
   callDescription:string;
   callReason:string ;
   tonnage:string ;
   delayReason:string;
   cargoCutoffDatetime:string;
   readyToSail:string;
   routeDetails:string;
   containerMoveType:string;
   containerSize:string;
   containerType:string;
   operationalStatus:string;
   isEdi:string;
   channel:string;
   reference:string;
   docDetails:DocDetails [];
}
