import { CSHBaseInfoAttachModel} from './cshbaseinfoattach.model';
import { CSHCountDetailsModel} from './cshcountdetails.model';
import { CSHHazardousContainerModel} from './cshhazardouscontainer.model';
import { CSHOOGContainerModel} from './cshoogcontainer.model';
import { CSHSpecialHandlingModel} from './cshspecialhandling.model';

export class CSHCreateModel{
    agentReferenceNo:string;
    clientCode:string;
    cshBaseInfoAttach:CSHBaseInfoAttachModel[];
    cshHazardousContainer:CSHHazardousContainerModel[];
    cshHazardousContainerId:string;
    cshNo:string;
    cshOOGContainer:CSHOOGContainerModel[];
    cshOOGContainerId:string;
    cshRequestNo:string;
    cshSpecialHandling:CSHSpecialHandlingModel[];
    eta:string;
    etd:string;
    fileName:string;
    fileUploadId:string;
    flashPoint:string;
    hazardousContainerNo:string;
    hazardousRemarks:string;
    imcoCode:string;
    imdgPage:string;
    isoCode:string;
    obBack:string;
    ofFront:string;
    ohHeight:string;
    olLeft:string;
    oogContainerNo:string;
    oogIso:string;
    oogRemarks:string;
    orRight:string;
    packingGroup:string;
    requestCutOffTime:string;
    requestStatus:string;
    riskLabel:string;
    rotationNumber:string;
    rotationNumberSearchButton:string;
    selectCheckbox:string;
    shippingLine:string;
    specialContainer:string;
    subCategorySh:string;
    subCategoryShDamage:string;
    subCategoryShHeavy:string;
    subCategoryShOther:string;
    vesselName:string;
}