import { TruckRegAttachResultModel } from "./truckregattachresult.model";
import { RegisteringAuthorityMasterResultModel } from "./registeringauthoritymasterresult.model";
import { TruckRegPoolRequestModel } from "./truckregpoolresult.model";
import {TruckRegTerminalResultModel} from "./truckregterminalresult.model";

export class TruckRegResultModel {
  active: string;
  addressLine1: string;
  addressLine2: string;
  amendRequestStatus: string;
  approver: string;
  approverButton: boolean;
  autoCancelRequest: string;
  chassisNo: string;
  clientCode: string;
  countryOfRegistration: string;
  truckRegstatus: string;
  createdDate: Date;
  engineNo: string;
  engineType: string;
  switchEnable: string;
  expired: string;
  expiryDate: string;
  insuranceExpiryDate: string;
  isB2bMessage: string;
  isDeleted: string;
  lastModifiedDate: Date;
  leaseOwn: string;
  length: number;
  licensePlateNo: string;
  makeYear: string;
  manufacturer: string;
  maximumGrossWeight: string;
  name: string;
  numberOfAxles: number;
  operatingTerminal: string;
  ownerCity: string;
  ownerCountry: string;
  ownerPostCode: string;
  ownerState: string;
  phoneNumber: string;
  plateCode: string;
  plateType: string;
  poolName: string ;
  port: string;
  registeringAuthority: string;
  registrationExpiryDate: string;
  registrationStartDate: string;
  requestDate: Date;
  requestFromDate: Date;
  requestNo: string;
  requestToDate: Date;
  reregister: string;
  rfidNumbers: string;
  state: string;
  status: string;
  truckDeletionStatus: string;
  truckInsuranceCompany: string;
  truckInsuranceNumber: string;
  truckInsuranceStartDate: string;
  truckModel: string;
  // truckOnHoldStatus: string;
   truckRegAttachSOList: TruckRegAttachResultModel[];
  // truckRegAuthorityMasterSOList: RegisteringAuthorityMasterResultModel[];
  // truckRegPoolSOList: TruckRegPoolRequestModel[];
  // truckRegRequestId: number;
  truckOnHoldStatus: string;
  truckRegAuthorityMasterSOList: RegisteringAuthorityMasterResultModel[];
  truckRegPoolSOList: TruckRegPoolRequestModel[];
  truckRegRequestId: number;
  truckRegTerminalSOList: TruckRegTerminalResultModel[];
  truckRegistrationId: number;
  truckRejectionStatus: number;
  type: string;
  vehicleColor: string;
  wrkflwId: string;
  wrkflwStatus: string;
  checkuser:string;

}
